name: Deploy & Publish Package

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-publish:
    uses: cercula/shared-actions/.github/workflows/release-package.yaml@main
    secrets:
      git-access-token: ${{ secrets.NPM_TOKEN }}
    with:
      package-registry: 'https://registry.npmjs.org'
      build-command: |
        npm run build
      npm-publish-args: --access public
